[package]
name = "another-boids-in-rust"
version = "0.2.0-dev1"
edition = "2021"

[dependencies]
bevy = "0.16.0"
bevy_spatial = "0.11.0"

# Grand-dependency pins
ab_glyph = "0.2.16"
fnv = "1.0.6"
gilrs = "0.10.5"
lazy_static = "1.0.2"
lock_api = "0.4.7"
miniz-sys = "0.1.10"
nonmax = "0.5.1"
rand = "0.8.0"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
# codegen-units = 1
lto = "fat"

[profile.mini]
inherits = "release"
lto = true
opt-level = "z"
codegen-units = 1
strip = "symbols"
panic = "abort"

[profile.wasm-release]
inherits = "release"
opt-level = "z"
strip = "debuginfo"
